apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name" . }}
  labels:
    app: {{ include "resource.default.name" . }}
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: {{ include "resource.default.name" . }}